# Site settings
title: dominicpeters.ca
header-img: img/home-bg.jpg
email: dpeters0905@gmail.com
copyright_name: Dominic Peters
description: "A place for me to share some of my projects and ideas"
baseurl: ""
url: "https://dpeters1.github.io"
#twitter_username: dpeters1
github_username:  dpeters1
#facebook_username:  dominicpeters
email_username:  dpeters0905@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-107367781-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: none
pagination:
  enabled: true
  per_page: 5
  permalink: '/:num/'
  title: ':title' 
  limit: 0
  sort_field: 'date'
  sort_reverse: true
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate-v2, jekyll-feed]
